version: "3.8"

services:
  postgres:
    restart: unless-stopped

  rabbitmq:
    restart: unless-stopped

  redis:
    restart: unless-stopped

  minio:
    restart: unless-stopped

  seq:
    restart: unless-stopped

  api:
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Database__ApplyMigrations: ${DB_APPLY_MIGRATIONS}
      Seed__Enabled: false
      Cors__AllowedOrigins: ${CORS_ALLOWED_ORIGINS}

  admin:
    build:
      context: ./ui/finwallet-admin
      dockerfile: Dockerfile
    container_name: finwallet-admin
    depends_on:
      - api
    ports:
      - "${ADMIN_HOST_PORT:-8082}:80"
    restart: unless-stopped
